import React, { useState } from "react";
import { Button, Flexbox, Switch } from "@lilib/ui";

function Example() {
  const [disabled, setDisabled] = useState(false);
  const [borderless, setBorderless] = useState(false);

  return (
    <Flexbox direction="column" gap="4x" align="flex-start">
      <Flexbox gap="2x" align="center">
        <Switch
          checkedLabel="Disabled"
          uncheckedLabel="Enabled"
          checked={disabled}
          onChange={(event) => setDisabled(event.target.checked)}
        />
        <Switch
          checkedLabel="Borderless"
          uncheckedLabel="Bordered"
          checked={borderless}
          onChange={(event) => setBorderless(event.target.checked)}
        />
      </Flexbox>

      <Flexbox gap="2x" align="center" wrap>
        <Button
          variant="solid"
          intent={null}
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
        <Button
          variant="solid"
          intent="major"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
        <Button
          variant="solid"
          intent="minor"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
        <Button
          variant="solid"
          intent="positive"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
        <Button
          variant="solid"
          intent="alertive"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
        <Button
          variant="solid"
          intent="negative"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
      </Flexbox>

      <Flexbox gap="2x" align="center" wrap>
        <Button
          variant="solid"
          color="red"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
        <Button
          variant="solid"
          color="magenta"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
        <Button
          variant="solid"
          color="purple"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
        <Button
          variant="solid"
          color="indigo"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
        <Button
          variant="solid"
          color="navy"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
        <Button
          variant="solid"
          color="blue"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
        <Button
          variant="solid"
          color="cyan"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
        <Button
          variant="solid"
          color="teal"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
        <Button
          variant="solid"
          color="green"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
        <Button
          variant="solid"
          color="lime"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
        <Button
          variant="solid"
          color="yellow"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
        <Button
          variant="solid"
          color="orange"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
        <Button
          variant="solid"
          color="brown"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
        <Button
          variant="solid"
          color="gray"
          disabled={disabled}
          borderless={borderless}
        >
          Button
        </Button>
      </Flexbox>
    </Flexbox>
  );
}

export default Example;
