export * from "./Collapse";
export * from "./Compact";
export * from "./Duration";
export * from "./Icon";
export * from "./Loader";
export * from "./Prefix";
export * from "./Size";
export * from "./Spinner";
export * from "./Theme";
export * from "./Transition";

export { default as Collapse } from "./Collapse";
export { default as Compact } from "./Compact";
export { default as Duration } from "./Duration";
export { default as Icon } from "./Icon";
export { default as Loader } from "./Loader";
export { default as Prefix } from "./Prefix";
export { default as Size } from "./Size";
export { default as Spinner } from "./Spinner";
export { default as Theme } from "./Theme";
export { default as Transition } from "./Transition";
