const order = [
  "Designs",
  ["Tokens", "Palettes"],
  "Configs",
  [
    "Root",
    "Baseline",
    "Focusing",
    "Prefix",
    "Theme",
    "Size",
    "Duration",
    "Direction",
  ],
  "General",
  ["Icon", "Text", "Image", "Button"],
  "Layouts",
  ["Grid", "Layout", "Divider", "Flexbox"],
  "Navigations",
  ["Menu", "Tabs", "Steps", "Dropdown", "Pagination", "Breadcrumbs"],
  "Forms",
  [
    "Form",
    "Input",
    "Select",
    "Textarea",
    "Radio",
    "Checkbox",
    "Rate",
    "Switch",
    "Slider",
    "Segmenter",
    "TimePicker",
    "DatePicker",
    "ColorPicker",
  ],
  "Views",
  [
    "Dot",
    "Tag",
    "Avatar",
    "Badge",
    "Info",
    "List",
    "Tree",
    "Card",
    "Table",
    "Timeline",
    "Carousel",
    "Calendar",
    "Accordion",
  ],
  "Feedbacks",
  ["Alert", "Loader", "Spinner", "Skeleton", "Progress"],
  "Overlays",
  [
    "Affix",
    "Dialog",
    "Prompt",
    "Drawer",
    "Toast",
    "Notice",
    "Popup",
    "Tooltip",
    "Confirm",
    "Popper",
    "Backdrop",
  ],
  "Animations",
  ["Collapse", "Transition"],
  "Others",
  ["Portal"],
  "Examples",
];

export default order;
