const order = [
  "Designs",
  ["Tokens"],
  "Configs",
  ["Root", "Baseline", "Focusing", "Prefix", "Theme", "Size", "Duration", "Direction"],
  "Generics",
  ["Icon", "Text", "Image", "Button"],
  "Layouts",
  ["Grid", "Layout", "Divider", "Flexbox"],
  "Navigations",
  ["Menu", "Tabs", "Steps", "Dropdown", "Pagination", "Breadcrumbs"],
  "Forms",
  [
    "Form",
    "Input",
    "Select",
    "Textarea",
    "Radio",
    "Checkbox",
    "Rate",
    "Switch",
    "Slider",
    "Segments",
    "TimePicker",
    "DatePicker",
    "ColorPicker",
  ],
  "Views",
  [
    "Dot",
    "Tag",
    "Badge",
    "Avatar",
    "List",
    "Tree",
    "Card",
    "Table",
    "Timeline",
    "Carousel",
    "Calendar",
    "Accordion",
    "Description",
  ],
  "Feedbacks",
  ["Alert", "Loader", "Spinner", "Skeleton", "Progress"],
  "Overlays",
  ["Affix", "Modal", "Dialog", "Drawer", "Toast", "Notice", "Popup", "Tooltip", "Confirm", "Popper", "Backdrop"],
  "Animations",
  ["Collapse", "Transition"],
  "Utilities",
  ["Portal", "Display", "Trigger"],
  "Examples",
];

export default order;
